### ISSUE TITLE
Examples to run multiple camera units in the same launch file

### ISSUE THREAD

**Issue by sisaha9** [luxonis/depthai-ros-examples#54]
How to run multiple camera units in the same launch file?

**Comment by Luxonis-Brandon** [comment]
Thanks.  I'm not sure.  Asking.

**Comment by saching13** [comment]
@sisaha9  you can use the stereo intertial launch file [here](https://github.com/luxonis/depthai-ros-examples/blob/cd6b28bc704ed689aa65132b3c5f698455309d78/depthai_examples/launch/stereo_inertial_node.launch#L4) and add it to your own multiple times by passing the MxID of specific devices as an argument to launch multiple units together.

**Comment by danilo-pejovic** [comment]
We are repurposing this repository as a place to hold our ROS examples we develop over time. As this issue seems resolved I will be closing it. Might be worth to check out our monolithic node and use it to run multiple cameras since it is easier to set up. [Link to relevant launch file](https://github.com/luxonis/depthai-ros/blob/humble/depthai_ros_driver/launch/example_multicam.launch.py)
